version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: developer
      MYSQL_DATABASE: golang_note
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      mynetwork:
        aliases:
          - db

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 3s

  migrate:
    image: migrate/migrate   # Use a lightweight image for migrations
    command: [
      "-path", "/migrations",
      "-database", "mysql://root:developer@tcp(db:3306)/golang_note",
      "up"
    ]
    volumes:
      - ./migrations:/migrations   # Mount your migration files
    depends_on:
      db:
        condition: service_healthy
    networks:
      mynetwork:
        aliases:
          - migrate

  app:
    build: .
    # image: kareem96/app-golang-note:1.0
    platform: linux/amd64
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: root
      DB_PASSWORD: developer
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: golang_note
    networks:
      mynetwork:
        aliases:
          - app

volumes:
  db_data:

networks:
  mynetwork: