// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"golang-restful-api-crud/app"
	"golang-restful-api-crud/controller"
	"golang-restful-api-crud/middleware"
	"golang-restful-api-crud/repository"
	"golang-restful-api-crud/service"
	"net/http"
)

// Injectors from injector.go:

func Initialiaze() *http.Server {
	noteRepositoryImpl := repository.NewNoteRepository()
	db := app.OpenConnectionDB()
	validate := ProvideValidator()
	noteServiceImpl := service.NewNoteService(noteRepositoryImpl, db, validate)
	noteControllerImpl := controller.NewNoteController(noteServiceImpl)
	router := app.NewRouter(noteControllerImpl)
	authMiddleware := middleware.NewAuthMiddleware(router)
	server := NewServer(authMiddleware)
	return server
}

// injector.go:

var noteSet = wire.NewSet(repository.NewNoteRepository, wire.Bind(new(repository.NoteRepository), new(*repository.NoteRepositoryImpl)), service.NewNoteService, wire.Bind(new(service.NoteService), new(*service.NoteServiceImpl)), controller.NewNoteController, wire.Bind(new(controller.NoteController), new(*controller.NoteControllerImpl)))

func ProvideValidator() *validator.Validate {
	return validator.New()
}
